AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Resource Importing (uksb-1q9p31idr).

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W3011

Parameters:
  Topic1Name:
    Description: Name of the first SNS topic you created manually using the SNS console.
    Type: String
    Default: Topic1

Resources:
  SNSTopic1:
    DeletionPolicy: Retain
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref Topic1Name
